config/routes.rb
Rails.application.routes.draw do

  resources :events, only: %i[new index show create]
  resources :users, only: %i[new create show]
  resources :attendances, only: %i[create destroy]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  root to: 'events#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: 'user_id'
  belongs_to :attended_event, class_name: 'Event', foreign_key: 'event_id'
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :description, :date, presence: true
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, class_name: 'User', foreign_key: :user_id

  scope :past, -> { where('date<?', Time.now).order('created_at DESc') }
  scope :upcoming, -> { where('date>?', Time.now).order('created_at DESc') }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :events, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :attended_events, class_name: 'Event', foreign_key: 'event_id', through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :events_attendance, :events_created

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def authorization
    redirect_to login_path unless logged_in?
  end

  def events_attendance
    current_user.attended_events
  end

  def events_created
    current_user.events
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    @attend = Attendance.new
    @attend.user_id = current_user.id
    @attend.event_id = params[:event_id]
    redirect_to current_user, notice: 'Event added to attending list' if @attend.valid? && @attend.save
  end

  def destroy
    @attend = Attendance.find_by(event_id: params[:id])
    redirect_to current_user, notice: 'Event removed from attending list' if @attend.valid? && @attend.destroy
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  @event = Event.new

  before_action :authorization
  helper_method :events_user_attending, :test

  def index
    @events = Event.all
    @past_events = Event.past.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
    @upcoming_events = Event.upcoming.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.valid? && @event.save
      redirect_to user_path(current_user), notice: 'Event Created Successfully'
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully Logged in!'
      redirect_to events_path
    else
      flash[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You logged out'
    redirect_to root_path
  end

  def index
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorization, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid? && @user.save
      redirect_to login_path, notice: 'Sign up successful, login using your credentials'
    else
      render 'new'
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_buttons
    buttons = []
    if logged_in?
      buttons.push(link_to(current_user.username, user_path(current_user),
                           class: 'text-dark mr-2 bg-warning py-1 px-2'))
      buttons.push(link_to('Create Event', new_event_path,
                           class: 'text-dark mr-2 bg-warning py-1 px-2'))
      buttons.push(link_to('Logout', logout_path, method: :delete,
                                                  class: 'text-dark mr-2 bg-warning py-1 px-2'))
    else
      buttons.push(link_to('Login', login_path,
                           class: 'text-dark  mr-2 bg-warning py-1 px-2'))
      buttons.push(link_to('Sign Up', new_user_path,
                           class: 'text-dark mr-2 bg-warning py-1 px-2 btn-link'))
    end
    buttons
  end

  def user_attending?(event_id)
    buttons = []
    if events_created.find_by(id: :event_id)
      buttons.push(link_to('Register',
                           attendances_path(controller: 'attendances', action: 'create',
                                            event_id: event_id), method: :post, class: 'btn btn-dark'))
      buttons.push(link_to('cancel', attendance_path(event_id), method: :delete,
                                                                class: 'btn btn-danger mt-1'))
    else
      buttons.push(link_to('Register',
                           attendances_path(controller: 'invites', action: 'create',
                                            event_id: event_id), method: :post, class: 'btn btn-dark'))
      buttons.push(link_to('Cancel', attendance_path(event_id), method: :delete,
                                                                class: 'btn btn-danger mt-1'))
    end
    buttons
  end
end

app/views/events/_futureevents.html.erb
<%@upcoming_events.each do |event|%>
<div class="col-sm-12 col-md-6">
      <%= link_to event_path(event), class:'text-decoration-none' do%>
      <div class="card bg-light mb-4 hover-1">
        <div class="card-title text-dark light-red">
          <div class="text-white px-2 py-1 d-flex justify-content-between align-items-center">
            <h4><%= event.title.capitalize%></h4>
            <p>Creator : <%=event.creator.username%></p>
          </div>
        </div>
        <div class="card-body bg-light text-dark px-0">
          <p class="text-justify px-2"><%=event.description%></p>
        </div>
        <div class="card-footer text-dark px-2 light-red">
          <p class="text-white">Event Date: <%= event.date%></p>
        <div class="mt-3">
          <% user_attending?(event.id).each do |button| %>
            <%= button%>
          <%end%>
        </div>
      </div>
  </div>
      <%end%>
</div>
<%end%>

app/views/events/_pastevents.html.erb
<%@past_events.each do |event|%>
<div class="col-sm-12 col-md-6">
      <%= link_to event_path(event), class:'text-decoration-none' do%>
      <div class="card bg-light mb-4 hover-1">
        <div class="card-title text-dark light-red">
          <div class="text-white px-2 py-1 d-flex justify-content-between align-items-center">
            <h4><%= event.title.capitalize%></h4>
            <p>Creator : <%=event.creator.username%></p>
          </div>
        </div>
        <div class="card-body bg-light text-dark px-0">
          <p class="text-justify px-2"><%=event.description%></p>
        </div>
        <div class="card-footer light-red text-dark px-2">
          <p class="text-white">Event Date: <%= event.date%></p>
      </div>
  </div>
      <%end%>
</div>
<%end%>

app/views/events/index.html.erb
<div class="container">
  <h1 class="text-center normal my-3 bg-secondary w-50 mx-auto py-2 text-white">
    Upcoming events: <%=pluralize(@upcoming_events.count, 'Event')%>
  </h1>
<div class="row">
  <%= render "futureevents"%>
  <div class="digg_pagination w-75 m-auto text-center">
  <%= will_paginate @upcoming_events%>
  </div>
  </div>


  <h1 class="text-center normal my-3 bg-secondary w-50 mx-auto py-2 text-white">
    Past events: <%=pluralize(@past_events.count, 'Event')%>
  </h1>
  <div class="row">
    <%=render "pastevents" %>
    <div class="digg_pagination w-75 m-auto text-center">
    <%= will_paginate @past_events%>
    </div>
</div>

</div>

app/views/events/new.html.erb
<div class="container2 my-4 light-red p-3">

<%= form_for(@event, local: true) do |form| %>
<div class="text-white">
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

  <div class="field">
    <%= form.text_field :title, class:"d-block w-100 mb-3 pl-2 input border",placeholder:"Name of the event" %>
  </div>

  <div class="field">
    <%= form.text_area :description, class:"d-block w-100 mb-3 pl-2 border",placeholder:"Enter event description",rows:"8" %>
  </div>


  <div class="field mb-3">
    <%= form.date_field :date, class:"form-control datepicker w-50 text-danger border-1 border-danger"%>
  </div>

  <div class="actions">
    <%= form.submit "Submit",class:"btn btn-warning btn-block rounded-0 py-2" %>
  </div>
<% end %>
</div>

app/views/events/show.html.erb
<div class="container2 my-3">

<div class="card bg-light mb-4 hover-1">
  <div class="card-title text-dark light-red">
    <div class="text-white px-2 py-1 d-flex justify-content-between align-items-center">
      <h4><%= @event.title.capitalize%></h4>
      <p>Creator : <%=@event.creator.username%></p>
    </div>
  </div>
  <div class="card-body bg-light text-dark px-0">
    <p class="text-justify px-2"><%=@event.description%></p>
  </div>
  <div class="card-footer light-red text-dark px-2">
    <p class="text-white">Event Date: <%= @event.date%></p>
  <div class="mt-3">
<p class="align-self-center text-white">Number of people: <%= @event.attendees.count%></p>
<hr class="bg-light">

<h6 class="text-white">List of names:</h6>
<% @event.attendees.each do |attendee|%>
  <ul class="list-unstyled text-white">
    <li><%= attendee.username%></li>
  </ul>
<%end%>
  </div>
</div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private-Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light light-red">
    <h4 class="text-white">Private Events <i class="fas fa-calendar-alt"></i></h4>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars text-white"></i>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav m-auto">
      <li class="nav-item mr-4">
        <i class="fas fa-home text-white mr-1"></i><%= link_to 'Home', events_path,class:"text-white" %>
      </li>
    </ul>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li>
          <% display_buttons.each do |button|%>
            <%= button%>
          <%end%>
          </li>
    </ul>
  </div>
</nav>


    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for(@user, local: true) do |f| %>

<div class="container bg-warning text-center w-75 mt-2">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h4 class="pt-2"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li class="list-group-item bg-warning border-0"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

  <div class="container text-center mt-5">

    <h1 class="mb-4">Sign Up for free!!</h1>

    <div class="row">
  	 <div class="col-md-4 mx-auto">
  		<div class="myform form ">

 <div class="card w-100">
     <div class="card-header p-0">
         <div class="light-red text-white text-center py-2">
             <i class="fas fa-sign-in-alt fa-2x"></i>
         </div>
     </div>

     <div class="card-body p-3">

       <div class="form-group">
           <div class="input-group mb-2">
               <div class="input-group-prepend">
                   <div class="input-group-text"><i class="fas fa-sort-alpha-down text-info"></i></div>
               </div>
               <%= f.text_field :username, autofocus: true, autocomplete: "name",class:"form-control",id:"name",placeholder:"username" %>
           </div>
       </div>

         <div class="form-group">
             <div class="input-group mb-2">
                 <div class="input-group-prepend">
                     <div class="input-group-text"><i class="fas fa-key text-info"></i></div>
                 </div>
                 <%= f.password_field :password, autocomplete: "new-password",class:"form-control",placeholder:"Enter your Password" %>
             </div>
         </div>

         <div class="form-group">
             <div class="input-group mb-2">
                 <div class="input-group-prepend">
                     <div class="input-group-text"><i class="fas fa-key text-info"></i></div>
                 </div>
                 <%= f.password_field :password_confirmation, autocomplete: "new-password",class:"form-control",placeholder:"Re-enter password" %>
             </div>
         </div>

         <div class="text-center">
           <%= f.submit "Sign up",class:"btn light-red btn-block text-white rounded-0 py-2" %>
         </div>

     </div>

 </div>
<% end %>
  		</div>
  	 </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="container">

<h1 class="text-center my-4 border-bottom-2 border-danger">Events History</h1>

<div class="row">
  <div class="col-sm-6">
    <h4 class="p-2 bg-secondary w-50 mx-auto mb-2 text-center text-white">Events you created:<%= events_created.count%></h4>
    <% events_created.order('created_at DESC').each do |event|%>
    <div class="col-sm-12">
            <%= link_to event_path(event), class:'text-decoration-none' do%>
            <div class="card light-red mb-4 text-center">
              <div class="card-title text-white py-2">
                  <p class="h4">Event Title:- <%= event.title%></p>
              </div>
              <div class="card-footer bg-light text-dark px-2">
                <p class="h5">Event Date:- <%= event.date%></p>
              </div>
            </div>

            <%end%>
    </div>
    <%end%>
  </div>


  <div class="col-sm-6">
    <h4 class="p-2 bg-secondary w-50 mx-auto mb-2 text-center text-white">upcoming Events: <%= events_attendance.where('date>?', Time.now).count%></h4>
    <% events_attendance.where('date>?', Time.now).each do |event|%>
    <div class="col-sm-12">
            <%= link_to event_path(event), class:'text-decoration-none' do%>
            <div class="card mb-4 py-4 hover-1 text-center light-red">
              <div class="card-title text-white pb-2">
                  <p class="h4">Event Title:-  <%= event.title%></p>
              </div>
              <div class="card-footer bg-light text-dark px-2">
                <p class="h5">Event Date:- <%= event.date%></p>
              </div>
              <div class="mt-3">
                <% user_attending?(event.id).each do |button| %>
                  <%= button%>
                <%end%>
              </div>
            </div>

            <%end%>
    </div>
    <%end%>
  </div>
</div>


<div class="row">
    <h4 class="p-2 bg-secondary w-75 mx-auto mb-2 text-center text-white">Previously attended events: <%= events_attendance.where('date<?', Time.now).count%></h4>
    <% events_attendance.where('date<?', Time.now).each do |event|%>
    <div class="col-sm-12 col-md-6">
            <%= link_to event_path(event), class:'text-decoration-none' do%>
            <div class="card light-red mb-4 text-center">
              <div class="card-title text-white py-2">
                  <p class="h4">Event Title:- <%= event.title%></p>
              </div>
              <div class="card-footer bg-light text-dark px-2">
                <p class="h5">Event Date:- <%= event.date%></p>
              </div>
            </div>

            <%end%>
    </div>
  <%end%>
</div>


</div>